### ISSUE TITLE
How to negate a match

### ISSUE THREAD

**Issue by hddharvey** [skvadrik/re2c#361] opened 2021-06-19 11:32 UTC
Is there any nice way to require that a token does not begin with something. Using character classes, we can negate single characters, but I have been able to determine how this can be done for longer sequences. E.g., if trying to tokenize markdown blocks, I might want to do something like:

```
newline = "\n" | "\r\n";
heading_start = "#";
code_start = "```" newline;
para = !code_start !heading_start para_contents;
// etc...
```

Where `!` is an operator I made up that indicates the absence of a pattern. The issue I have is that, looking at this as an example, the `para_contents` is broad and otherwise matches the start of code blocks and headings. A paragraph should be everything that doesn't match as a code block or a heading (in this simple example).

**Comment by skvadrik** [comment] 2021-06-19 13:33
There is no negate operator in re2c (it would likely be possible to add one, but it is not trivial, and I need to do some research on that subject first). What you can try to do is to add rule(s) that accept forbidden cases and fail with a syntax error, like this:
```
/*!re2c
    // ...
    (code_start | heading_start) para_contents  { /* error */ }
    para_contents  { /* ok */ }
*/
```
It doesn't have to be a syntax error, you can do something else, e.g. jump to a different lexer block and try to re-lex in a different way. I realize it's manual and tedious and not as nice as negation, so it would be good to have a negation operator. https://github.com/skvadrik/re2c/issues/181 is related.

**Comment by hddharvey** [comment] 2021-06-19 14:15
The above wouldn't work for me either since code_start followed by para_contents would be completely valid syntax, so I would have to somehow recover from it and decide to parse differently (e.g., by going to a different lexer as you said). But thanks for the advice - I'll manage.

**Comment by skvadrik** [comment] 2021-06-19 18:56
Perhaps you can put the rules that start with `code_start` or `heading_start` before the one that starts with `para_contents`? Then, if there is some overlap between these rules, the earliest one would match.

**Comment by sergeyklay** [comment] 2021-06-19 19:32
@hddharvey Could you please provide a minimal markdown example and rules you are try to implement. I'm pretty sure @skvadrik can help you write a working PoC

**Comment by hddharvey** [comment] 2021-06-21 06:26
@skvadrik I wasn't able to do that, since the `para_contents` rule would normally match exactly the same length as `code_start`. I could work around that by artificially changing one of the rules to accept one more or less character (like a trailing newline, or the EOF character "\x00"), however it's obviously not the most elegant solution. As I said, I can do without a negation operator, it just seems like a negation operator would be a powerful way to do that in an elegant way.

@sergeyklay I won't bother with an example here, since (a) I was working on a virtual machine that has become corrupted and I have lost all my re2c code that I was playing around with since the last commit :-( and (b) since I've figured out a reasonable way to do it on my own. But thanks.

**Comment by hddharvey** [comment] 2021-06-21 06:31
Also I have not been using regexes for very long, but a negation operator seems to correspond to the idea of "negative lookahead" supported by some regex engines.

**Comment by skvadrik** [comment] 2021-06-21 06:47
Yes, that's what https://github.com/skvadrik/re2c/issues/181 is about (only it should be allowed in the middle of a rule, not only at the end).

**Comment by hddharvey** [comment] 2021-06-21 07:24
Whoops. Closed it by accident. Feel free to close if you want since this is covered by another issue apparently. 

On a side note, why does re2c say that backreferences are not allowed in named definitions? (iirc)

**Comment by hddharvey** [comment] 2021-06-21 07:27
Also when discussing my specific use case up above, I got things backwards. I couldn't use the natural precedence of rules because the matches for code blocks and paragraphs were _different lengths_ (I said the same length - if that was the case, I could just order the rules differently to achieve what I wanted as you said).

**Comment by skvadrik** [comment] 2021-06-21 23:03
> Whoops. Closed it by accident. Feel free to close if you want since this is covered by another issue apparently.

Let's keep it open as another reminder about negative lookahead (for the future).

> On a side note @skvadrik , why does re2c say that backreferences are not allowed in named definitions? (iirc)

What do you mean by backreferences, the POSIX feature that allows one to reference parts of the matched text in the regular expression, like `(.*)\1` to match any string followed by a copy of itself? Then it's not only named definitions that do not allow it, but any regular expressions used in re2c. This feature is notoriously difficult to implement. As far as I know, it raises the language complexity from regular to at least context-sensitive and cannot be implemented efficiently on deterministic automata.

Perhaps you mean something different? Searching for "backref" in https://re2c.org/manual/manual_c.html finds zero hits.

> Also when discussing my specific use case up above, I got things backwards.

As @sergeyklay said, it is better to see your actual code --- easier to spot errors or missed solutions that way than from a description. But that's up to you, if you have figured out a way on your own and don't want to waste time then it's completely fine.

**Comment by hddharvey** [comment] 2021-06-22 03:47
> What do you mean by backreferences, the POSIX feature that allows one to reference parts of the matched text in the regular expression, like (.*)\1 to match any string followed by a copy of itself? Then it's not only named definitions that do not allow it, but any regular expressions used in re2c. This feature is notoriously difficult to implement. As far as I know, it raises the language complexity from regular to at least context-sensitive and cannot be implemented efficiently on deterministic automata.

Interesting. Is this something that other regex engines struggle with then? Do they work differently from re2c under the hood in a way that makes it easier?

> Perhaps you mean something different?

Sorry I meant to say lookahead, not backreference. In re2c, that is the `R / S` operator I believe.

**Comment by skvadrik** [comment] 2021-06-22 06:49
> Interesting. Is this something that other regex engines struggle with then? Do they work differently from re2c under the hood in a way that makes it easier?

They are forbidden in may engines (e.g. the RE2 library). And yes, they require a different underlying algorithm.

Regular expression (RE) engines can be (very roughly) subdivided into three categories: those that use recursive backtracking (like PCRE), those that use non-deterministic automata (NFA, many regular expression libraries do, like RE2) and those that use deterministic automata (DFA, this is what lexer generators like re2c usually do). Libraries often use hybrid approach: in simple cases they use DFA, and in more complex cases they fall back to NFA.

Both DFA and NFA have linear matching complexity (in the length of input), but DFA are much faster in practice: DFA are O(n), and NFA are O(nm) where m is the size of the NFA, which depends on the size of RE. The speed of DFA comes at a price: they have limitations compared to NFA. Lexer generators use DFA mostly because they do the determinization ahead of time and it is not included in the matching time, so it makes sense to do it.

Backreferences are easily implemented with recursive backtracking, but it has worst-case exponential complexity, O(2^n). So, they are not only a problem for lexer generators like re2c that are based on DFA, but also for RE libraries like RE2 that can use NFA.

> Sorry I meant to say lookahead, not backreference.

Ah, the lookahead operator `R / S` is not allowed in named definitions because it is only allowed at the top level (as a trailing context, but not nested). Nested lookahead operation would be difficult to implement on determinisitc automata. Consider an example:
```
    R X Y  { ... }
    (R / S) Y  { ... }
```
Where `R`, `S`, `X`, `Y` are regular expressions. What if `X` and `S` partially overlap, e.g. there is some `Z` that is both in `X` and `S`? If the lexer has matched `R Z` so far, what is it to do: continue from the current position to try and match `Y` or rollback cursor to the beginning of `Z` and try to match `Y`? It would be ok for NFA: just pursue both possibilities (it is already non-deterministic anyway). But DFA must do one thing at any point. This is what makes it fast.

By the way a similar problem would arise in case of negative lookahead. Maybe it can be solved in some way on DFA, but I don't know how and it doesn't look easy.

**Comment by sergeyklay** [comment] 2021-06-22 10:57
> > Interesting. Is this something that other regex engines struggle with then? Do they work differently from re2c under the hood in a way that makes it easier?
> 
> They are forbidden in many engines (e.g. the RE2 library). And yes, they require a different underlying algorithm.
> 
> Regular expression (RE) engines can be (very roughly) subdivided into three categories: those that use recursive backtracking (like PCRE), those that use non-deterministic automata (NFA, many regular expression libraries do, like RE2) and those that use deterministic automata (DFA, this is what lexer generators like re2c usually do). Libraries often use hybrid approach: in simple cases they use DFA, and in more complex cases they fall back to NFA.
> 
> Both DFA and NFA have linear matching complexity (in the length of input), but DFA are much faster in practice: DFA are O(n), and NFA are O(nm) where m is the size of the NFA, which depends on the size of RE. The speed of DFA comes at a price: they have limitations compared to NFA. Lexer generators use DFA mostly because they do the determinization ahead of time and it is not included in the matching time, so it makes sense to do it.
> 
> Backreferences are easily implemented with recursive backtracking, but it has worst-case exponential complexity, O(2^n). So, they are not only a problem for lexer generators like re2c that are based on DFA, but also for RE libraries like RE2 that can use NFA.
> 
> > Sorry I meant to say lookahead, not backreference.
> 
> Ah, the lookahead operator `R / S` is not allowed in named definitions because it is only allowed at the top level (as a trailing context, but not nested). Nested lookahead operation would be difficult to implement on determinisitc automata. Consider an example:
> 
> ```
>     R X Y  { ... }
>     (R / S) Y  { ... }
> ```
> 
> Where `R`, `S`, `X`, `Y` are regular expressions. What if `X` and `S` partially overlap, e.g. there is some `Z` that is both in `X` and `S`? If the lexer has matched `R Z` so far, what is it to do: continue from the current position to try and match `Y` or rollback cursor to the beginning of `Z` and try to match `Y`? It would be ok for NFA: just pursue both possibilities (it is already non-deterministic anyway). But DFA must do one thing at any point. This is what makes it fast.
> 
> By the way a similar problem would arise in case of negative lookahead. Maybe it can be solved in some way on DFA, but I don't know how and it doesn't look easy.

@skvadrik Great intro about difference of RE engines and clarification on how they works.  I'm pretty sure this note should be in re2c docs.

**Comment by hddharvey** [comment] 2021-06-28 11:48
This "splitting" issue where the DFA has to pursue two different possibilities is an interesting problem. You say that DFAs are preferable to NFAs because they are faster. 

Let's say you had a re2c block with a bunch of normal rules with no naughty use of negative lookahead that could be completely implemented as a DFA. Now I add on two more rules that use negative lookahead and that clash in the ambiguous way you described above, requiring an NFA instead of a DFA. Surely all the code paths up and until that ambiguous point between those two rules is reached could be the same old DFA code that runs just as fast. You would then need some more complicated code to be emitted at the point where that clashing negative lookahead occurred, which would be slower - but slower is better than not being able to do it at all!

What I'm trying to say is - does the special "non-DFA" code paths required for those clashing rules have to pessimize all the other code paths that remain "unambiguous" so to speak. If not, then is the worse performance really a disadvantage? Worse performance at problematic negative lookahead is better than no performance.

Maybe you can tell that I don't know much about the formal math behind DFAs and NFAs beyond a skimming of Wikipedia and faint memories from related university courses - but I'd be interested to know any issues with what I describe above!

**Comment by skvadrik** [comment] 2021-07-01 10:32
Hybrid DFA-NFA approaches are used in some regular expression engines, but it's not a simple matter. For one thing, it would make even the fast paths slower (those going through DFA and never hitting the NFA parts) because of the increased code size, which means more cache misses, etc. The other reason is that different rules are usually more tightly coupled in the DFA than one might expect. For example, one might have rules like `"qwerty"` and `[a-z]*` that overlap and share the same DFA paths, and not expect that adding some problematic negative lookahead on `[a-z]*` would pessimize `"qwerty"`. The problematic cases for negative lookahead and the rules that cause overlap are likely to be the same (some sort of repetition). 

> slower is better than not being able to do it at all!

That is not always true. The main re2c goal is to generate very fast lexers. It does not support things that cannot be fast. This adds some limitations, but at the same time it leads to really interesting findings. For example, re2c had no support for submatch extraction until the development of lookahead-TDFA which allows it to be really fast. If we kept to the "slow is better than nothing" approach, we would never get to inventing that algorithm. In general, re2c tries to guarantee that the generated code is not worse than a reasonably optimized C program written by hand.

> Maybe you can tell that I don't know much about the formal math behind DFAs and NFAs beyond a skimming of Wikipedia and faint memories from related university courses - but I'd be interested to know any issues or misconceptions with what I describe above!

Oh no, not at all. Good questions are always welcome. :)

**Comment by hddharvey** [comment] 2021-07-06 13:38
Hmmmm. Good point about i-cache. I don't know much about what NFA code would look like, but I don't think it's necessarily as simple as bigger is slower - I would assume it should depend precisely on how the program branches at runtime, what parts of code are hot and cold, etc. I would prefer to profile before making assumptions. And wouldn't that be true for adding _any_ code to your lexer, it could be other rules that don't invoke weird lookahead at all. It all increases code size, and depending precisely on the program, how it branches, and so on, that could all hurt i-cache. Unless that is, NFAs are generally very big compared to DFAs in terms of code size?

And don't forget what you're comparing with. Would an NFA be worse on the cache and performance in general _compared to_ what you would have to write without that kind of support in re2c to do the same thing? I do understand your philosophy though, and I'm sure a pure DFA approach is very mathematically appealing.

And my re2c output file is already 140k lines anyway (from a 200 line input file) because I use a few rules with UTF-8. So I'm probably behind on the code size front anyway :-(.

**Comment by skvadrik** [comment] 2023-07-04 06:39
Closing this as duplicate of https://github.com/skvadrik/re2c/issues/181.

**Closed by skvadrik** 2023-07-04 06:39 UTC
