### ISSUE TITLE
UTF8 enoding

### ISSUE THREAD

**Issue by dtp555-1212** [skvadrik/re2c#250] opened 2019-05-22 19:59 UTC
It appears there is a bug in the UTF8 encoding (at least for some characters)...

[utf8bug.zip](https://github.com/skvadrik/re2c/files/3209080/utf8bug.zip)

In the attached file... there is a 2 byte UTF character which should be encoded as C3 A9 ... (if you copy/paste the UTF char into a file by itself, then use od -t x1, you will see that it is indeed C3 A9). The C3 in the generated parser is correct, but then generates 83 as the second target byte. I am using -8 on the command line. (If there is something I am doing wrong, or if there is a workaround, please let me know)

**Comment by skvadrik** [comment] 2019-05-22 21:05
Eh, it's a duplicate of #237. The problem is, re2c `-8` option does not give you source-level Unicode support: if you write characters like `é` in regexp definitons, re2c interprets it as a plain byte sequence (each byte as a single character), not as one Unicode symbol. You have to use `"\u00e9"` instead.

I realize this is very ugly, difficult to use, confusing and needs fixing.

What exactly happens in case of `é` and how re2c ends up with `C3 83` byte sequence is explained in great detail in #237 (let me know if you need more clarifications).

**Comment by dtp555-1212** [comment] 2019-05-23 00:11
Thanks for your reply... Obviously there are many Unicode values, not just the one I provided in my example. Do I understand you correctly, that I cannot provide the escaped hex byte sequence. I must use a unicode equivalent. (in this case \u00e9 for the two byte sequence C3 9A)... Is this understanding correct? Will this work for the 3 & 4 byte unicode values as well? (and not only match the character 'visually' but have the expected byte count for utf-8?) With this understanding, it sounds like I will have to preprocess the input strings to substitute the appropriate unicode encoding prior to processing with re2c. Do you have a suggested tool for that?

Thanks again
P.S. as you have acknowledged that this needs addressing, do you have a timeframe that it might be implemented?

________________________________

**Comment by skvadrik** [comment] 2019-05-23 16:41
> Do I understand you correctly, that I cannot provide the escaped hex byte sequence. I must use a unicode equivalent.

Yes, it won't work. If you try regular expression `\xC3\x9A` in `-8` mode, re2c will interpret it as "code point `C3` followed by a code point `9A`", both of which translate into 2-byte code unit sequences in UTF-8. The same happens when instead of `\xC3\x9A` you write `é` (only re2c doesn't have to unescape bytes).

> Will this work for the 3 & 4 byte unicode values as well? 

Escaped sequences will work for all Unicode code points (re2c supports 2-byte, 4-byte and 8-byte syntax: `\xhh`, `\uhhhh` and `\Uhhhhhhhh`).

> it sounds like I will have to preprocess the input strings to substitute the appropriate unicode encoding prior to processing with re2c. Do you have a suggested tool for that?

No, unfortunately I don't. In a similar issue #235 we ended up with a pre-defined set of Unicode categories, but it's not good enough for your case.

> P.S. as you have acknowledged that this needs addressing, do you have a timeframe that it might be implemented?

I might be able to fix this in a few days. I have a sketch of the fix already, but it requires some pre-requisite work in order to make it more elegant. It's a matter of using `-8` in re2c own lexer (which is written in re2c) and switching between two different lexers (ASCII and UTF8). The new behavior will be guarded by an option, something like `--input-encoding <ascii | utf8>`.

**Comment by skvadrik** [comment] 2019-05-24 11:30
> Do I understand you correctly, that I cannot provide the escaped hex byte sequence. I must use a unicode equivalent.

Yes, it won't work. If you try regular expression `\xC3\x9A` in `-8` mode, re2c will interpret it as "code point `C3` followed by a code point `9A`", both of which translate into 2-byte code unit sequences in UTF-8. The same happens when instead of `\xC3\x9A` you write `é` (only re2c doesn't have to unescape bytes).

> Will this work for the 3 & 4 byte unicode values as well? 

Escaped sequences will work for all Unicode code points (re2c supports 2-byte, 4-byte and 8-byte syntax: `\xhh`, `\uhhhh` and `\Uhhhhhhhh`).

> it sounds like I will have to preprocess the input strings to substitute the appropriate unicode encoding prior to processing with re2c. Do you have a suggested tool for that?

No, unfortunately I don't. In a similar issue #235 we ended up with a pre-defined set of Unicode categories, but it's not good enough for your case.

> P.S. as you have acknowledged that this needs addressing, do you have a timeframe that it might be implemented?

I might be able to fix this in a few days. I have a sketch of the fix already, but it requires some pre-requisite work in order to make it more elegant. It's a matter of using `-8` in re2c own lexer (which is written in re2c) and switching between two different lexers (ASCII and UTF8). The new behavior will be guarded by an option, something like `--input-encoding <ascii | utf8>`.

**Comment by skvadrik** [comment] 2019-05-24 12:34
Pushed a fix: https://github.com/skvadrik/re2c/commit/29a6d01984f158f50406fa8246a24ee1a7246efe.

Now it is possible to use UTF-8 encoded strings in regular expressions (in string literals and character classes). The new behaviour is enabled with option `--input-encoding utf8`. By default re2c assumes `--input-encoding ascii`; in future it may be possible to flip default behaviour (if it keeps confusing people).

It was necessary to use a new option instead of reusing `-8`, because one may wish to generate multiple lexers with different *output* encoding from the same set of UTF-8 encoded rules. That is, one may need to combine `--input-encoding utf8` with one of the options `-u`, `-x`, `-w`, etc., and not necessarily `-8`.

I deliberately chose a broad name for the new option (as opposed to a more precise `--utf-8-literals` or some such) so that it can be extended it in future, for example support UTF-8 encoded variable names (I do not see any good in that so far though).

**Comment by skvadrik** [comment] 2019-05-24 12:42
@dtp555-1212 If you can, please send me your real-world test. If it's closed-source, I only need the grammar rules (though a working self-contained example is always great).

**Comment by dtp555-1212** [comment] 2019-05-24 13:52
Attached is a list of words that have utf8 chars in them, and the other would be the rule to insert into the test program previously provided.

Hope that helps

Thanks

________________________________

**Comment by skvadrik** [comment] 2019-05-24 14:20
Thanks! I added a test (it returns 0 for all the names on the list): https://github.com/skvadrik/re2c/blob/a00dc4871106ea39ef84f47bb840a018b17cea25/test/encodings/utf8_names.i8--input-encoding(utf8).re

There is an error in the name `Ibargüen`, it has a strange `C2` byte right before `C3 BC` representing `ü`. It doesn't look like valid UTF-8 to me. After deleting `C2` from both places everything works fine.

**Comment by terpstra** [comment] 2019-05-24 20:53
This is great! When can we expect the next re2c release? I can't wait to re2c:include a Unicode character classes library and define character classes with literal UTF8 strings in them!

**Comment by skvadrik** [comment] 2019-05-24 21:30
Soon, soon, really soon! I know I said this a couple of times before, such a shame... `/o\` Realistically, not earlier than in 2 weeks, not later than the end of July. Thanks for asking, it gives me the inspiration to start writing changelog. :)

**Closed** 2019-06-10 08:03 UTC
