### ISSUE TITLE
With `=> condition`, generate `goto condition` after user-defined action.

### ISSUE THREAD

**Issue by sirzooro** [skvadrik/re2c#151] opened 2016-06-28 16:11 UTC
re2c already supports syntax `<ctx> "foo" :=> newctx`, which sets new context and jumps to corresponding label. However there is no dedicated syntax to additionally execute some code. Syntax page lists following one but without further explanation:

```
<condition-list> regular-expression => condition { C/C++ code }
```

I tried to use it and found that generated code changes context variable and executes code, but does not jump to new label. So I propose to extend this operator or add new to both execute change context and jump to label. You could reuse `:=>` operator for this if you do not want to modify how `=>` works.

Skeleton generation probably could benefit from this too.

I would also like to see one more change - please change value of context variable after executing user code, not before. This would be helpful if some rule is assigned to multiple contexts, to check which one is active. Now assignment is done first, so code like below cannot be used:

```
<C1,C2,C3> "foo" { return (yycC1 == ctx) ? 1 : 2; }
```

**Comment by skvadrik** [comment] 2016-06-28 16:59
Did you read this example: http://re2c.org/examples/example_05.html ? It explains everything:

- `:=> condition` means "instead of user-defined code, generate direct unconditional jump to `condition`"
- `=> condition` means "call `YYSETCONDITION(condition)` before jumping to user-defined code, then jump to user-defined code"  (whatever happens next is up to the user, but you're making the same false assumption as in #143 that re2c will generate some `goto end` instruction). If you do use `=>`, then your code should transfer control flow to the initial condition dispatch generated by re2c.
- You're not obliged to use any of `:=>` or `=>`. If you know which condition you should go to, by all means, just go it (put `goto condition` at the end of your code).

You might find these rules confusing, and I would agree. I personally find conditions inconvenient and prefer to handle control flow explicitly. The thing is, re2c supports *any* control flow, but at the expense of some extra work. 

Hope the example is helpful.

> Skeleton generation probably could benefit from this too.

As for now, skeleton handles each condition as a separate lexer. Mixing input strings from different conditions is hard (all possible combinations will blow up the space, so we would need a clever mixing strategy, but I didn't put much thought into it). Also, user code can do anything in between two conditions (e.g. increase input position by a random number), there's no way re2c can guess user's intention.

>I would also like to see one more change - please change value of context variable after executing user code, not before.

Ah, it's too late to do anything *after* transferring control to the user-defined code. re2c cannot make any assumptions about it: user-defined code can return, it can segfault, or it can jump right to the initial condition dispatch, bypassing the `YYSETCONDITION` code. Moreover, it's the expected behaviour.

**Comment by skvadrik** [comment] 2016-06-28 17:46
By the way, in your example calling `YYSETCONDITION` after user code is useless, because user code returns. However, you can rewrite it this way:
```
<C1,C2,C3> "foo" {
    int r = (yycC1 == ctx) ? 1 : 2;
    YYSETCONDITION(C4);
    return r;
}
```
(you don't have to use `YYSETCONDITION`, for sure).

**Comment by sirzooro** [comment] 2016-06-28 21:38
Thanks. I checked that example before, but it also does not explain how `=>` works.

It is not confusing, at least now when I know more how generated code looks like. I just expected that code generated from re2c blocks will mix cleanly with my code (so there will be some `goto end_of_block` as I wrote in #143). Another assumption was that it will help me automate some typical tasks. Access to low level details is nice and in many cases important, but usually simpler solution is enough. `:=>` is great for transferring control to another context, but it does not allow to insert some extra code. `=>` allows to insert code, but it does not jump. Hence this issue.

This is also a coding style issue - `goto` is not recommended. Because of this I put `while` loop in my code and use `break` and `continue` to control flow.

You are right that condition cannot be changes after user code, this would not be reliable. Code should look like you wrote, or `YYSETCONDITION` should store current context in some other variable before setting new one, so user code could access it. Or just do it this way, but docs should warn that it works this way and user has to handle it in his code if he wants to do some explicit jump :)

What do you think about changing `=>` to add `goto` after user code to jump to code which handles specified context, like `:=>` do? This should not break existing code, because it has to jump somewhere explicitly. This `goto` would be a dead code so compiler may optimize it out (the same case is in issue mentioned earlier). If you are worried adding this, what about adding extra command line option to enable (or disable) doing this? This way user could decide if he wants these extra gotos or not.

**Comment by skvadrik** [comment] 2016-06-28 22:14
> docs should warn that it works this way 

Yes, conditions lack proper documentation (like many re2c features).

>What do you think about changing `=>` to add goto after user code to jump to code which handles specified context, like `:=>` do? 

It seems like a good idea, but I need to think it over and experiment. Every change in API may either break backwards compatibility or become a legacy burden in future, so we have to think them out very carefully.

**Closed** 2017-08-26 20:27 UTC
