### ISSUE TITLE
big source tarball

### ISSUE THREAD

**Issue by rofl0r** [skvadrik/re2c#221] opened 2018-10-13 02:18 UTC
hi, i've just updated re2c from 0.14 to 1.1.1 >>[0]<< and noticed the tarball grew from 2.5 to 5.9MB, which is quite big considering the built executable is only 300 KB!
maybe there's some binary documentation inside that bloats the source unnecessarily and could be offered as a secondary download to interested people ?
since folks like me who build their stuff from source usually keep the tarballs around, every MB counts...thanks for considering to shrinking it a bit.
maybe offering a download as tar.xz could also bring the size down a bit.

[0]: https://github.com/sabotage-linux/sabotage/commit/cf7c1ceebd78c11892e933b77807a64f122b6a7a

**Comment by trofi** [comment] 2018-10-13 07:11
We can check what is actually used in tarball by re-compressing individual directories to get the idea:

```
re2c-1.1.1 $ ls -lh *.gz --sort=size
3.6M test.tar.gz
889K doc.tar.gz
115K src.tar.gz
59K bootstrap.tar.gz
42K examples.tar.gz
```

As we can see these are mostly tests. `6MB` does not sounds like an unreasonable number.

**Comment by skvadrik** [comment] 2018-10-13 07:34
My conclusion is the same: tests eat all the space (and they will only grow over time). Without tests the resulting tarball is about 100K. We can potentially package stripped tarball without tests, but that requires fiddling with automake conditionals to make things like `make check` pass for the stripped tarball. Is it worth the effort?

@rofl0r: Since you build from source, it is likely that you also want to run the tests, right?

@trofi thanks for measuring!

**Comment by skvadrik** [comment] 2018-10-13 07:35
I measured `.tar.xz` size, and it is about 2.7M, so maybe using xz the best option.

**Comment by leo-yuriev** [comment] 2018-10-13 09:31
git-submodule with test's code and data?

**Comment by rofl0r** [comment] 2018-10-13 13:32
> @rofl0r: Since you build from source, it is likely that you also want to run the tests, right?

not really. all our packages do --disable-tests, when possible, to save time, and to allow cross-compilation (tests work only for native compiles anyway).

**Comment by skvadrik** [comment] 2018-10-16 23:18
@trofi pushed a fix that switches to .tar.xz by default and reduces tarball size 2x.

> another aspect of having a big source tarball is that it suggests a bloated program inside.
> for example i was evaluating lexers and when re2c was mentioned i looked into my pkg recipe and was immediately repelled by the 2.5 MB tarball size, to the point of immediately abandoning it as a potential candidate. but since i already had it installed for php, i looked a bit closer and figured the program itself is reasonably small.

Hmm... I might be wrong, but it seems that a moderately-lazy distro maintainer would grab the same tarball, or do the same `git clone` command regardless of whether the tests are enabled or not, and later on decide what to do with the tests. So git submodules won't prevent you from mis-judging the size of the program by the size of the tarball.

What I'm not happy with is fat git history, which is caused by committing large binary blobs in the past (they were deleted shortly after committing when I realized my mistake, but the history has them).

**Comment by rofl0r** [comment] 2018-10-16 23:59
> @trofi pushed a fix that switches to .tar.xz by default and reduces tarball size 2x.

great, thanks!

> git submodules won't prevent you from mis-judging the size of the program by the size of the tarball.

git submodules weren't my idea, and i don't think they'd help tbh. i'm specifically talking about *release tarballs*, not github's tarball-from-tag feature.

since the testsuite of re2c seems to be incredibly voluminous, my personal preference would be to create 2 tarballs during `make dist`: `re2c-x.y.z.tar.xz` and `re2c-testsuite-x.y.z.tar.xz` or alternatively `re2c-x.y.z-onlysource.tar.xz` and `re2c-x.y.z-full.tar.xz`.
git does a similar thing: git sources are distributes in `git-x.y.z.tar.xz`, and manpages in `git-manpages-x.y.z.tar.xz`.

> What I'm not happy with is fat git history, which is caused by committing large binary blobs in the past (they were deleted shortly after committing when I realized my mistake, but the history has them).

yeah, this is a quite annoying problem: if you dont notice the mistake within a short time (during which you could force-push to correct it), you're stuck with it, unless you rewrite the history... that's why i always look at my commits with `gitk` before pushing. also i tell ppl to never use `git commit -a` ...

**Closed** 2020-01-27 22:04 UTC
