### ISSUE TITLE
cmake .. cant build in vs2019

### ISSUE THREAD

**Issue by yangjian1218** [skvadrik/re2c#373] opened 2021-08-02 10:09 UTC
I have loaded down re2c-2.2-release and re2c-2.2-release.I found it has build dir in filedir, so I mkdir build_dir
when I do "cmake .." ,there is a erro:
PS D:\YJYJ\re2c-2.2\build_dir> cmake ..
-- Building for: Visual Studio 15 2017
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

So I change to :cmake .. -G"Visual Studio 16 Win64" 
But It only highly support to vs 15 2017 :

CMake Error: Could not create named generator Visual Studio 16 Win64

Generators
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.

**Comment by sergeyklay** [comment] 2021-08-02 15:03
I'll check this ASAP (most likely this week).

**Comment by sergeyklay** [comment] 2021-08-07 15:42
I'm sorry, I can't reproduce.

```powershell
PS C:\Users\Serghei\work> git.exe clone https://github.com/skvadrik/re2c.git
Cloning into 're2c'...
remote: Enumerating objects: 49864, done.
remote: Counting objects: 100% (3425/3425), done.
remote: Compressing objects: 100% (1463/1463), done.
remote: Total 49864 (delta 2092), reused 2923 (delta 1858), pack-reused 46439R
Receiving objects: 100% (49864/49864), 91.86 MiB | 2.92 MiB/s, done.

Resolving deltas: 100% (37207/37207), done.
Updating files: 100% (4214/4214), done.
```

```powershell
PS C:\Users\Serghei\work\re2c> cd .\build_dir\
```

```powershell
PS C:\Users\Serghei\work\re2c> mkdir build_dir

    Directory: C:\Users\Serghei\work\re2c

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----            8/7/2021  6:37 PM                build_dir
```

```powershell
PS C:\Users\Serghei\work\re2c> cd .\build_dir\
```

```powershell
PS C:\Users\Serghei\work\re2c\build_dir> cmake.exe ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.29.30040.0
-- The CXX compiler identification is MSVC 19.29.30040.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: f:/Programs/VisualStudio/2019/BuildTools/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: f:/Programs/VisualStudio/2019/BuildTools/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test cxxflag__Wall
-- Performing Test cxxflag__Wall - Success
-- Performing Test cxxflag__EHsc
-- Performing Test cxxflag__EHsc - Success
-- C compiler flags: /DWIN32 /D_WINDOWS /W3
-- C++ compiler flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc  /Wall /EHsc
-- Linker flags for executables: /machine:x64
-- Linker flags for shared libs: /machine:x64
-- Could NOT find BISON (missing: BISON_EXECUTABLE)
-- Found Python3: C:/Python39/python.exe (found version "3.9.6") found components: Interpreter
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Looking for io.h
-- Looking for io.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of char
-- Check size of char - done
-- Check size of short
-- Check size of short - done
-- Check size of int
-- Check size of int - done
-- Check size of long
-- Check size of long - done
-- Check size of long long
-- Check size of long long - done
-- Check size of __int64
-- Check size of __int64 - done
-- Check size of void *
-- Check size of void * - done
-- Check size of 0l
-- Check size of 0l - done
-- Check size of 0ll
-- Check size of 0ll - done
-- Check size of 0i8
-- Check size of 0i8 - done
-- Writing config.h
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Serghei/work/re2c/build_dir
```

**Comment by sergeyklay** [comment] 2021-08-07 15:51
@yangjian1218 Did you try vs2019 or vs2017? In issue header "_cant build in vs2019_" but in the provided logs "_Building for: Visual Studio 15 2017_"

**Comment by sergeyklay** [comment] 2021-08-11 08:30
> CMake Error: Could not create named generator Visual Studio 16 Win64

Do you have installed Visual Studio 2019? Also as far as I understand you have used CMake 3.13, but support of `Visual Studio 16 2019` generator was first introduced for CMake 3.14 version.

**Comment by skvadrik** [comment] 2022-01-25 07:33
Closing due to lack of information.

**Closed by skvadrik** 2022-01-25 07:33 UTC
