### ISSUE TITLE
test failure on big endian archs with 0.15.3

### ISSUE THREAD

**Issue by jcfp** [skvadrik/re2c#132] opened 2016-01-05 18:03 UTC
Hi,

After updating re2c in debian to 0.15.3, building the executable works fine on all architectures (with some compiler warnings in the Wconversion, Wsign-conversion and Wformat departments) but unfortunately 3 out of 976 tests do not pass on any big endian arch (mips, powerpc, s390x, hppa). See build logs [here](https://buildd.debian.org/status/package.php?p=re2c&suite=unstable) or [here](https://buildd.debian.org/status/logs.php?pkg=re2c&ver=0.15.3-1&suite=sid). The BE archs whose builds appear to succeed (m68k, sparc64) only do so because their build daemons skipped the test-suite. None of the little endian builders failed the test-suite.

Due to an slight oversight on my end the debian build logs don't show the content of the test-suite.log, so I had to resort to running an emulated BE system (debian jessie on mips) in qemu to reproduce the issue. Log and files of the failed tests linked below originate from there. The failed tests are:
```
FAIL       repeat-07_default.gir--skeleton.re
FAIL       unicode_blocks.u--skeleton--encoding-policy(ignore).re
FAIL       unicode_blocks.x--skeleton--encoding-policy(ignore).re
```
I assume it's these very same tests that also fail on the build daemons (all running debian unstable). A quick inspection of the *.c.diff files shows parts with byte order reversed like this:

![screenshot](http://i.imgur.com/l8TloA0.png)

Test-suite.log and retained test files are available [here](https://github.com/jcfp/dump/tree/master/re2c_logs_jessie_mips). If you need more info let me know!

**Comment by skvadrik** [comment] 2016-01-05 21:14
Reproduced failures on powerpc64. Those tests probably failed because they store binary data in native endianness (native to amd64, as it happens to be my host platform). Should be easy to fix.

Thanks for a detailed report!

**Comment by skvadrik** [comment] 2016-01-07 14:55
Fixed in this commit: https://github.com/skvadrik/re2c/commit/de094eba9f39655184910013d4eb55b0fdcd4722 (tested on powerpc64). Fix will be included in re2c-0.16.

**Comment by jcfp** [comment] 2016-01-07 22:05
Thanks!

Do you have an ETA for 0.16 in mind? Not meaning to pressure you here, but just so I know whether it makes sense to wait or backport the bugfix to the 0.15.3 package.

**Comment by skvadrik** [comment] 2016-01-07 22:54
I plan to release 0.16 in a couple of weeks. I think the fix can wait - it only affects tests (everything else works fine on big-endian platforms, including ```--skeleton``` switch).

**Closed** 2016-01-23 11:10 UTC
