### ISSUE TITLE
`m4': No such file or directory

### ISSUE THREAD

**Issue by Wyrdplay** [skvadrik/re2c#267] opened 2020-01-24 12:21 UTC
In getting the project setup and hitting this issue. I do not believe i hit this issue on my other machine a few weeks ago.

```
sh-3.1$ ./autogen.sh
aclocal-1.11: couldn't open directory `m4': No such file or directory
autoreconf-2.68: aclocal failed with exit status: 1
sh-3.1$
```

Creating an empty m4 folder gets past this issue but then fails during the configure step.

I am running on Windows with MinGW installed, so there may just be a compatibility issue.

[EDIT]
This is from a fresh git clone of the repo.

I've realised now that m4 is not what i thought it was. I thought it was an external code dependency.

Running autoconf directly gives the following failure in m4,.. so it is finding it. And I've confirmed that the program exists and the version is good.

```
sh-3.1$ autoconf
' is already registered with AC_CONFIG_FILES.
/mingw/src/autoconf/26/autoconf2.5-2.68-1/src/autoconf-2.68/lib/autoconf/status.m4:290: AC_CONFIG_FILES is expanded from...
configure.ac:127: the top level
autom4te-2.68: /bin/m4 failed with exit status: 1
sh-3.1$
```

**Comment by skvadrik** [comment] 2020-01-24 22:17
If you only need to build re2c, you can try building it from a tarball (which has a pre-genrated `configure` script and does not require running autoconf):
```
$ wget https://github.com/skvadrik/re2c/releases/download/1.3/re2c-1.3.tar.xz
$ tar -xvf re2c-1.3.tar.xz
$ cd re2c-1.3
$ ./configure
$ make
```
As for the autoconf error, it seems to be a frequent issue with Cygwin on Windows caused by a git checkout with Windows-style newlines (see for example https://stackoverflow.com/questions/50256967/aclocal-error-is-already-registered-with-ac-config-files-and-or-r-comma):
> The line beginning with ' is already registered with implies that the cursor was sent back to the beginning of the line partway through writing the line to the console -- the exact behavior of printing a string read from a DOS-format text file while it expecting it to be in UNIX format.

The suggested fix is configuring git to check out text files in UNIX format:
```
git config --global core.autocrlf false
git config --global core.eol lf
```
Could you try this and see if it helps?

**Comment by skvadrik** [comment] 2020-07-14 06:23
Can't reproduce after half a year, so closing.

**Closed by skvadrik** 2020-07-14 06:23 UTC
